---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: elixir:1.8-alpine
  commands:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  volumes:
  - name: mix
    path: /root/.mix

- name: test
  image: elixir:1.8-alpine
  commands:
  - mix test
  volumes:
  - name: mix
    path: /root/.mix

- name: build
  image: elixir:1.8-alpine
  commands:
  - mix escript.build
  volumes:
  - name: mix
    path: /root/.mix
  when:
    event:
    - tag

volumes:
- name: mix
  temp: {}
