name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        elixir: ['1.19']
        otp: ['27']
    
    container:
      image: elixir:${{ matrix.elixir }}-alpine
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    
    - name: Run tests
      run: mix test
    
    - name: Build escript
      if: startsWith(github.ref, 'refs/tags/')
      run: mix escript.build
    
    - name: Upload binary
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: dotfiler-binary
        path: bin/dotfiler
