name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: elixir

      # Build and upload the escript when a release is created
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Set up Elixir
        if: ${{ steps.release.outputs.release_created }}
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '27'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Build escript
        if: ${{ steps.release.outputs.release_created }}
        run: mix escript.build

      - name: Upload binary to release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} bin/dotfiler
